title: [重建家園臺服1區-明日之後聯盟]
description: [聯盟宗旨：無極很快，信米姐得永生]
baseurl: "/"
url: "https://sleepeatplay.github.io/"

# Theme settings
theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Chat forum settings (you can integrate an external service like Disqus)
disqus:
  shortname: https-sleepeatplay-github-io-chat

# Leaderboard settings (you can create a custom collection)
collections:
  leaderboard:
    output: true
    permalink: /leaderboard/:path/

# Exclude these files from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor

# Custom variables
navbar_links:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Chat Forum"
    url: "/chat/"
  - title: "Leaderboard"
    url: "/leaderboard/"

# Theme configuration (Minima theme example)
minima:
  social_links:
    twitter: your_twitter_handle
    github: your_github_username
    facebook: your_facebook_page

# Enable comments (assuming Disqus)
comments:
  provider: "disqus"

# Author details
author:
  name: "阿白"
  email: "rickytangsh0217@gmail.com"

# Repository settings (useful for GitHub Pages)
repository: sleepeatplay.github.io

